// <auto-generated />
using System;
using EasyTicket.Services.Discount.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyTicket.Services.Discount.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20201220125812_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EasyTicket.Services.Discount.Entities.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlreadyUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = new Guid("b828facb-1965-40bc-84f2-1f14eabf6a21"),
                            AlreadyUsed = false,
                            Amount = 10,
                            Code = "BeNice"
                        },
                        new
                        {
                            CouponId = new Guid("c4f26b5a-f965-4c39-aa30-f9175ae889b0"),
                            AlreadyUsed = false,
                            Amount = 20,
                            Code = "Awesome"
                        },
                        new
                        {
                            CouponId = new Guid("c267fefe-6e8d-43f3-ba60-c357e782b888"),
                            AlreadyUsed = false,
                            Amount = 100,
                            Code = "AlmostFree"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
